config/routes.rb
CharityHost::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  get "settings/index"

  get "charity/:id/post/index", to: 'post#index', as: 'post_index'
  post "charity/:id/post/create", to: 'post#create'
  match "charity/:id/post/:post_id/:action", to: 'post', as: "post", via: [:get, :patch, :delete]

  match "charity/:id/post/:post_id/comment/:comment_id/:action", to: 'comment', as: "comment", via: [:get, :patch, :delete]

  match "charity/:id/appearance/:action", to: 'appearance', as: "appearance", via: [:get, :patch]
 
  match "charity/:id/settings/:action", to: 'settings', as: "settings", via: [:get, :patch]

  get "uploads/:id/*_", to: 'upload#show'
  match "charity/:id/upload/:action", to: 'upload', as: "upload", via: [:get, :post]

  get '/charity/:id/index', to: 'charity#show'
  post '/charity/check_passcode', to: 'charity#check_passcode'
  match '/charity/:id/:action', to: 'charity', as: 'charity', via: [:get, :post]

  resources :charity, :path => 'charity'

  get '/users/sign_in', to: 'home#index', as: 'new_user_session_path'
  devise_for :users
  root :to => 'home#index'

  

end

app/models/admins_charity.rb
class AdminsCharity < ActiveRecord::Base
  belongs_to :user
  belongs_to :charity

  after_save :update_charity_passcode
  before_destroy :update_charity_passcode

  private

  def update_charity_passcode
  	self.charity.generate_passcode
  	self.charity.save
  end
end

app/models/animal_detail.rb
class AnimalDetail < ActiveRecord::Base
  belongs_to :post
end

app/models/charity.rb
class Charity < ActiveRecord::Base
	validates_uniqueness_of :name
	validates_uniqueness_of :domain
	validates_presence_of :name
	validates_presence_of :domain

  has_many :admins_charities
  has_many :admins, source: :user, through: :admins_charities

	has_many :posts
  has_many :views, class_name: "CharityView"
  has_many :donations
  has_many :newsletter_subscriptions
  has_one :settings, class_name: "CharitySettings"

	before_create :build_settings
  before_create :generate_passcode

  def generate_passcode
    begin
      range = [*'0'..'9', *'A'..'Z']
      self.passcode = Array.new(8){range.sample}.join
    end while Charity.find_by_passcode(self.passcode)    
  end

  def all_posts_ordered
    posts.order('created_at DESC')
  end

  def admin_posts
    all_posts_ordered.select{|p| p.author.admin_of self}
  end

  def user_posts
    all_posts_ordered.select{|p| !p.author.admin_of self}
  end

  def all_tags
    posts.map{|p| p.tags}.flatten
  end

  def all_tags_ordered
    hash = Hash.new(0)
    all_tags.each {|t| hash[t.tag] +=1 }
    hash.sort_by{|tag, count| count}.map{|kvPair| kvPair.first}
  end

  def views_per_day
    viewHash = Hash.new(0)
    views.order('created_at DESC').limit(30).each {|v| viewHash[v.created_at.strftime("%d/%m/%Y")] +=1 }
    return viewHash
  end
end

app/models/charity_settings.rb
class CharitySettings < ActiveRecord::Base
	belongs_to :charity
end

app/models/charity_view.rb
class CharityView < ActiveRecord::Base
  belongs_to :charity
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/comments.rb
class Comments < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/donation.rb
class Donation < ActiveRecord::Base
  belongs_to :charity
end

app/models/post.rb
class Post < ActiveRecord::Base

  validates_presence_of :title
  validates_presence_of :content

  belongs_to :charity
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'

  has_many :comments
  has_many :tags, class_name: "PostTag"
  has_many :photos, class_name: "PostPhoto"
  has_one :animal_detail

  def has_tag (tag)
  	tags.exists?(tag: tag)
  end
end

app/models/post_photo.rb
class PostPhoto < ActiveRecord::Base
  belongs_to :post
end

app/models/post_tag.rb
class PostTag < ActiveRecord::Base
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :admins_charities
  has_many :managed_charities, source: :charity, through: :admins_charities
  # has_many :charities, through: :admins_charities

  has_many :posts
  has_many :comments
  has_many :newsletter_subscriptions

  def admin_of (charity)
    managed_charities.exists?(charity)
  end

  def is_superadmin?
    self.superadmin
  end
end

app/controllers/home_controller.rb
class HomeController < RedirectController

	layout 'home'

	def index

	end
end

app/controllers/post_controller.rb
class PostController < RedirectController

  layout 'admin'
  before_filter :find_post, :only => [:edit, :update, :destroy]

  def index
    @posts = @charity.all_posts_ordered
    if !params[:tag].blank?
      @posts = @posts.select{|p| p.has_tag params[:tag]} 
    end
  end

  def show
    @post = @charity.posts.find(params[:post_id])
  end

  def create
		post = @charity.posts.new(new_post_params)
    post.author = current_user
    post.save

    if post.save
      params[:post][:tags].delete(' ').split(',').each do |tag|
        post.tags.create(tag: tag)
      end
      flash[:notice] = "Post created successfully"
    else
      flash[:error] = "Error creating post, a title and some content are necessary"
    end
    redirect_to charity_path(@charity)
  end

  def edit
    
  end

  def update
    @post.update_attributes(new_post_params)
    redirect_to charity_path(@charity)
  end

  def destroy
    @post.delete
    redirect_to charity_path(@charity, :show)
  end

	private

  def find_post
     @post = @charity.posts.find(params[:post_id])
  end

	def new_post_params
		params.require(:post).permit(:title, :content)
	end
end

app/helpers/appearance_helper.rb
module AppearanceHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charity_helper.rb
module CharityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/views/home/index.html.erb
<% if user_signed_in?  %>

	<% content_for :page_title do %>
		CharityHosting.ie
	<% end %>

	<div class="page-section">
		<%= render partial: "charity/admin/registrations/new" %>	
	</div>

	<div class="page-section">
<%= form_for :charity, url: '/charity/check_passcode', html:{class: "form-horizontal", role: "form"} do |f| %>
		<fieldset>
	<legend>Become an admin of an existing charity</legend>

		<div class="form-group">
			<div class="col-sm-offset-3 col-sm-6">
			    <p>Contact any current admin of the charity you want to join and ask them to give you the passcode which can be found in the Manage Admins section</p>
			</div>
		</div>

	  <div class="form-group">
		  <%= f.label :passcode, class: "col-sm-3 control-label" %>
		  <div class="col-sm-6">
		  	<%= f.text_field :passcode, :autofocus => true, class: "form-control" %>
		  </div>
	  </div>

	  <div class="form-group">
	    <div class="col-sm-offset-3 col-sm-6">
	      <%= f.submit "Join Charity", :class => "btn btn-primary form-control" %>
	    </div>
	  </div>
	  </fieldset>
<% end %>
</div>

	<div class="page-section">
		<h3>Managed Charities</h3>
		<% if current_user.managed_charities.count == 0 %>
			<p>You are not currently an admin of any charities</p>
		<% else %>
			<ul>
			<% current_user.managed_charities.each do |charity| %>
				<li><p><%= link_to charity.name, charity %></p></li>
			<% end %>
			</ul>
		<% end %>
	</div>

<% else %>
	<!-- user not signed in -->
	<%= form_for resource, :as => resource_name, :url => registration_path(resource_name), html:{class: "form-horizontal", role: "form"} do |f| %>
			<fieldset>
		<legend>New here? Sign Up</legend>
		  <%= devise_error_messages! %>

		  <div class="form-group">
			  <%= f.label :email, class: "col-sm-3 control-label" %>
			  <div class="col-sm-6">
			  	<%= f.email_field :email, :autofocus => true, class: "form-control" %>
			  </div>
		  </div>

		  <div class="form-group">
		  	<%= f.label :password, class: "col-sm-3 control-label" %>
		  	<div class="col-sm-6">
		  		<%= f.password_field :password, class: "form-control"  %></div>
		  	</div>
		  <div class="form-group">
		  	<%= f.label :password_confirmation, class: "col-sm-3 control-label" %>

		  	<div class="col-sm-6">
		  		<%= f.password_field :password_confirmation, class: "form-control" %>
		  	</div>
		  </div>
		  <div class="form-group">
		    <div class="col-sm-offset-3 col-sm-6">
		      <%= f.submit "Sign Up", :class => "btn btn-primary form-control" %>
		    </div>
		  </div>
		  </fieldset>
	<% end %>


	<%= form_for resource, :as => resource_name, :url => session_path(resource_name), html:{class: "form-horizontal sign-in-form", role: "form"} do |f| %>
			<fieldset>
		<legend>Already a member? Sign In</legend>
		  <%= devise_error_messages! %>

		  <div class="form-group">
			  <%= f.label :email, class: "col-sm-3 control-label" %>
			  <div class="col-sm-6">
			  	<%= f.email_field :email, class: "form-control" %>
			  </div>
		  </div>

		  <div class="form-group">
		  	<%= f.label :password, class: "col-sm-3 control-label" %>
		  	<div class="col-sm-6">
		  		<%= f.password_field :password, class: "form-control"  %></div>
		  	</div>

		  <div class="form-group">
		  <%= f.label :remember_me, class: "col-sm-3 control-label" %>
		  	<div class="col-sm-6">
		  		<%= f.check_box :remember_me %>
		  	</div>
		  </div>

		  <div class="form-group">
		    <div class="col-sm-offset-3 col-sm-6">
		      <%= f.submit "Sign In", :class => "btn btn-primary form-control" %>
		    </div>
		  </div>
		  </fieldset>
	<% end %>
<% end %>