config/routes.rb
CharityHost::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  get "settings/index"

  get "charity/:id/post/index", to: 'post#index', as: 'post_index'
  post "charity/:id/post/create", to: 'post#create'
  match "charity/:id/post/:post_id/:action", to: 'post', as: "post", via: [:get, :patch, :delete]

  match "charity/:id/post/:post_id/comment/:comment_id/:action", to: 'comment', as: "comment", via: [:get, :patch, :delete]

  match "charity/:id/appearance/:action", to: 'appearance', as: "appearance", via: [:get, :patch]
 
  match "charity/:id/settings/:action", to: 'settings', as: "settings", via: [:get, :patch]

  get "uploads/:id/*_", to: 'upload#show'
  match "charity/:id/upload/:action", to: 'upload', as: "upload", via: [:get, :post]

  get '/charity/:id/index', to: 'charity#show'
  post '/charity/check_passcode', to: 'charity#check_passcode'
  match '/charity/:id/:action', to: 'charity', as: 'charity', via: [:get, :post]

  resources :charity, :path => 'charity'

  get '/users/sign_in', to: 'home#index', as: 'new_user_session_path'
  devise_for :users
  root :to => 'home#index'

  

end

app/models/admins_charity.rb
class AdminsCharity < ActiveRecord::Base
  belongs_to :user
  belongs_to :charity

  after_save :update_charity_passcode
  before_destroy :update_charity_passcode

  private

  def update_charity_passcode
  	self.charity.generate_passcode
  	self.charity.save
  end
end

app/models/animal_detail.rb
class AnimalDetail < ActiveRecord::Base
  belongs_to :post
end

app/models/charity.rb
class Charity < ActiveRecord::Base
	validates_uniqueness_of :name
	validates_uniqueness_of :domain
	validates_presence_of :name
	validates_presence_of :domain

  has_many :admins_charities
  has_many :admins, source: :user, through: :admins_charities

	has_many :posts
  has_many :views, class_name: "CharityView"
  has_many :donations
  has_many :newsletter_subscriptions
  has_one :settings, class_name: "CharitySettings"

	before_create :build_settings
  before_create :generate_passcode

  def generate_passcode
    begin
      range = [*'0'..'9', *'A'..'Z']
      self.passcode = Array.new(8){range.sample}.join
    end while Charity.find_by_passcode(self.passcode)    
  end

  def all_posts_ordered
    posts.order('created_at DESC')
  end

  def admin_posts
    all_posts_ordered.select{|p| p.author.admin_of self}
  end

  def user_posts
    all_posts_ordered.select{|p| !p.author.admin_of self}
  end

  def all_tags
    posts.map{|p| p.tags}.flatten
  end

  def all_tags_ordered
    hash = Hash.new(0)
    all_tags.each {|t| hash[t.tag] +=1 }
    hash.sort_by{|tag, count| count}.map{|kvPair| kvPair.first}
  end

  def views_per_day
    viewHash = Hash.new(0)
    views.order('created_at DESC').limit(30).each {|v| viewHash[v.created_at.strftime("%d/%m/%Y")] +=1 }
    return viewHash
  end
end

app/models/charity_settings.rb
class CharitySettings < ActiveRecord::Base
	belongs_to :charity
end

app/models/charity_view.rb
class CharityView < ActiveRecord::Base
  belongs_to :charity
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/comments.rb
class Comments < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/donation.rb
class Donation < ActiveRecord::Base
  belongs_to :charity
end

app/models/post.rb
class Post < ActiveRecord::Base

  validates_presence_of :title
  validates_presence_of :content

  belongs_to :charity
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'

  has_many :comments
  has_many :tags, class_name: "PostTag"
  has_many :photos, class_name: "PostPhoto"
  has_one :animal_detail

  def has_tag (tag)
  	tags.exists?(tag: tag)
  end
end

app/models/post_photo.rb
class PostPhoto < ActiveRecord::Base
  belongs_to :post
end

app/models/post_tag.rb
class PostTag < ActiveRecord::Base
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :admins_charities
  has_many :managed_charities, source: :charity, through: :admins_charities
  # has_many :charities, through: :admins_charities

  has_many :posts
  has_many :comments
  has_many :newsletter_subscriptions

  def admin_of (charity)
    managed_charities.exists?(charity)
  end

  def is_superadmin?
    self.superadmin
  end
end

app/helpers/appearance_helper.rb
module AppearanceHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charity_helper.rb
module CharityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CharityHost</title>
  	<link data-turbolinks-track="true" href="/assets/application.css?body=1" media="all" rel="stylesheet" />
	<link data-turbolinks-track="true" href="/assets/charity.css?body=1" media="all" rel="stylesheet" />
	<link data-turbolinks-track="true" href="/assets/pick-a-color-1.2.2.min.css?body=1" media="all" rel="stylesheet" />

  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav>
	<h1><%= @charity.name %></h1>
	<ul>

		<li><a href="<%= charity_path %>">Home</a></li>
		<li><a href="http://<%= @charity.domain %>">Preview</a></li>
		<li><%= link_to 'Statistics', charity_path(@charity, :statistics) %></li>
		<li class="category"><span>Appearance</span></li>
		<li><a href="<%= appearance_path(@charity, :template) %>">Change Base Template</a></li>
		<li><a href="<%= appearance_path(@charity, :configure_template) %>">Change Text Color</a></li>
		<li><a href="<%= appearance_path(@charity, :configure_template) %>">Change Header Image</a></li>

		<li class="category"><span>Settings</span></li>
		<li><a href="<%= settings_path(@charity, :index) %>">About Your Charity</a></li>
		<li><a href="<%= settings_path(@charity, :index) %>">Configure Donations</a></li>
		<li><a href="<%= settings_path(@charity, :index) %>">Enable/Disable donations</a></li>
		<li><a href="<%= charity_path(@charity, :manage_admins) %>">Manage Admins</a></li>

		<li class="category"><span>Posts</span></li>
		<li><a href="<%= post_index_path(@charity) %>">All Posts</a></li>

		
		<% @charity.all_tags_ordered.each do |tag| %>
			<li><a href="<%= post_index_path(@charity) %>?tag=<%=tag%>"><%= tag.capitalize %></a></li>
		<% end %>
	</ul>
</nav>

<div id="main">

	<%= render partial: 'layouts/shared/flash_alerts' %>

	<div id="topbar">
		<h2><%= yield :page_title %></h2>
		<span>
			<%= current_user.email %>
			<%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "btn btn-default" %> 
			<a href="<%= edit_user_registration_path %>">
				<%= image_tag 'glyphicons_136_cogwheel.png', :class => "settings", alt: 'Settings' %>
			</a>
		</span>
	</div>
	<%= yield %>
</div>

</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CharityHost</title>
  	<link data-turbolinks-track="true" href="/assets/application.css?body=1" media="all" rel="stylesheet" />
	<link data-turbolinks-track="true" href="/assets/charity.css?body=1" media="all" rel="stylesheet" />
	<link data-turbolinks-track="true" href="/assets/home.css?body=1" media="all" rel="stylesheet" />

  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="main">

	<%= render partial: 'layouts/shared/flash_alerts' %>

	<% if user_signed_in? %>
		<div id="topbar">
			<h2><%= yield :page_title %></h2>
			<span>
				<%= current_user.email %>
				<%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "btn btn-default" %> 
				<a href="<%= edit_user_registration_path %>">
					<%= image_tag 'glyphicons_136_cogwheel.png', :class => "settings", alt: 'Settings' %>
				</a>
			</span>
		</div>
	<% end %>

	<%= yield %>
</div>

</body>
</html>

app/views/layouts/old_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CharityHost</title>
  <link data-turbolinks-track="true" href="/assets/application.css?body=1" media="all" rel="stylesheet" />
  <link data-turbolinks-track="true" href="/assets/charity.css?body=1" media="all" rel="stylesheet" />
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/layouts/patron.html.erb
<html>
	<head>
		<title><%= @charity.name %></title>
		  <link data-turbolinks-track="true" href="/assets/application.css?body=1" media="all" rel="stylesheet" />
 		 <link data-turbolinks-track="true" href="/assets/patron/<%= @settings.base_style %>" rel="stylesheet" />
 		 <% @charity.views.create(ip: request.remote_ip) %>

 		 <style type="text/css">
 		 <% if @settings.text_color %>
 		 	*{
 		 		color: <%= "#" + @settings.text_color %>;
 		 	}
 		 <% end %> 
 		 </style>
	</head>
	<body>
		<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	      <div class="container">
	        <div class="navbar-header">
	          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
	            <span class="sr-only">Toggle navigation</span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	          </button>
	          <a class="navbar-brand" href="#"><%= @charity.name %></a>
	        </div>
	        <div class="collapse navbar-collapse">
	           <ul class="nav navbar-nav">
	            <li><a href="/">Home</a></li>
	          </ul>
	        </div><!--/.nav-collapse -->
	      </div>
	    </div>
		<div class="container">
			<%= yield %>
		</div>
	</body>
</html>

app/views/layouts/shared/_flash_alerts.html.erb
<div id="alerts">
	<% if flash[:notice] %>
		<div class="alerts">
			<div class="alert alert-success alert-dismissable">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			<%= flash[:notice] %>
		</div>
	<% end %>
	<% if flash[:error] %>
		<div class="alerts">
			<div class="alert alert-danger alert-dismissable">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			<%= flash[:error] %>
		</div>
	<% end %>
</div>